baseURL = 'https://clearsky.dev/'
languageCode = 'en-us'
title = 'ClearSky'
theme = 'etch'
languagecode = "en"
[params]
  sitename = "ClearSky"
  noauthor = "true"
[taxonomies]
    tag = "tags"
    
[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 5